### ISSUE TITLE
Set mac using docker api and not net-util.sh

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/cattle#135]
Previously Docker did not allow the mac address to be set on container start and as such Rancher would set the mac address by dropping into the namespace with the `net-util.sh` script.  With Docker 1.4 `--mac-address=` is now available on `run` and setting the mac address through `net-util.sh` is no longer needed.

**Comment by hibooboo2** [comment]
This is addressed with this [PR] (https://github.com/rancherio/python-agent/pull/51)

**Comment by vincent99** [comment]
@barkerd427: This is fixed in master and will be included in the next release (tomorrow).
