### ISSUE TITLE
Projects owned by team are not unique

### ISSUE THREAD

**Issue by vincent99** [rancherio/cattle#215]
/v1/projects returns projects like:

```
{
  id: '1a24',
  type: 'project',
  externalIdType: 'project:github_team',
  externalId: 'dev'
}
```

Using a team as the owner of a project doesn't work right, because their names are only unique within an organization, not across them.  (e.g. both rancherio and rancherlabs have a team named "dev").

Need to store, accept and return team id (or org name + team name) instead.

**Comment by sidharthamani** [comment]
@vincent99  and I decided to use teamIds instead of orgName + "/" + teamName. That way the Id is the consistent mode of representing github teams while communicating with cattle. 

The input to cattle will be teamId and the output on creation and on listing will be teamId
