### ISSUE TITLE
Liquibase DB migrations require a public internet connection

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/cattle#228]
For liquibase to parse the change log XML it apparently does XSD validation and downloads the XSD from www.liquibase.org.  This requires a public internet connection.  It would be prefered to disable the XSD validation and not require going to www.liquibase.org

**Comment by sonchang** [comment]
Yeah.  I noticed this as well.  Just required during startup.  Very useful for doing dev work on a plane.

**Comment by ibuildthecloud** [comment]
@sonchang lol, yes I bought internet on the plane specifically because of this yesterday.

**Comment by sonchang** [comment]
I was able to solve this by just referencing a local copy of the *.xsd files.  But we still run into issues later if we want to use the UI or register agents to the cattle server.

**Comment by ibuildthecloud** [comment]
What was the change you made?  Do it work if you build the final war/jar too?   I know rancher isn't really usable without the Internet but it seems silly that the server fails to start because of this.  Also I believe this adds a second or to two the start up that is unnecessary.

**Comment by wscheele** [comment]
Happened to find myself on a plane y'day and experienced the same problem.
Cause is that cattle embeds liquibase 3.1, while the changelog XML files refer to the 3.2 and 3.3 xsd. They are not in the 3.1 jar, hence the inet request from the parser.
I worked around it by using a newer liquibase jar, but as sonchang noted, after that the ui is still unusable as well...

**Comment by ibuildthecloud** [comment]
Well thanks for pointing out the mismatch in the versions.  We will fix that.  Now the UI is a bit more tricky...

**Comment by ibuildthecloud** [comment]
I tried upgrading to 3.3 but unfortunately it requires more changes because of some classpath magic Cattle does.  I tested real quick to move all XSDs to 3.1 and it seemed to work.  I'll put in a PR

**Comment by kohlerm** [comment]
Still not working in the docker image, same error as above

**Comment by ibuildthecloud** [comment]
@kohlerm This will be fixed in v0.19 => https://github.com/rancherio/cattle/pull/390

**Comment by vincent99** [comment]
This is fixed now..
