### ISSUE TITLE
Currently You dont know if a host is active

### ISSUE THREAD

**Issue by hibooboo2** [rancherio/cattle#230]
Hosts can be registered via the api but if you lose connection to the host you cannot tell via the ui. I think we should address this.

**Comment by hibooboo2** [comment]
FIxed with new ui

**Comment by ibuildthecloud** [comment]
I'm going to reopen this issue.  I think there are situations where the state is not reflected properly.  This is a short coming in the backend.  Needs more investigation.  This must be tested with admin and user account.

**Comment by vincent99** [comment]
Also nothing changed in the UI to fix this, it's always (supposed to have) been showing a combination of the host and the agent's state.

**Comment by ibuildthecloud** [comment]
I don't know if you see agents correctly.  So if you do a include=agent you probably get back the objects but I bet you don't get resource change events for agents if your a user.
