### ISSUE TITLE
API: embedded object's property of reference type return actual DB id in the API response

### ISSUE THREAD

**Issue by alena1108** [rancherio/cattle#312]
So "service" object has embedded launchConfig property of "container" type. If the embedded object has properties that are ref to the other cattle object - dataVolumesFrom/registryCredentialId in my case - their ids in the response object are listed as actual DB ids in the API response: 22 instead of 1c22 as an example

**Comment by sangeethah** [comment]
Tracking this issue in - https://github.com/rancherio/rancher/issues/594
