### ISSUE TITLE
Feature: Add a new container Logs API 

### ISSUE THREAD

**Issue by pranavs18** [rancherio/cattle#96]

**Comment by pranavs18** [comment]
The need of this feature is to obtain docker logs from the container, collect and ship it using this new API  to the Rancher UI so that the user can always monitor it through the console.

**Comment by pranavs18** [comment]
Requirements 
Add a new action (API) for container for fetching its logs

Functionality 

The result of this new action(API) should return a url to a websocket on the host and also a jwt token. The websocket should connect to the host-api go process which runs on the host.

Tentative Design 

The implementation of this new API would probably be based on how the stats action and the exec action on instance have been implemented in Cattle.

Currently, the host-api go process creates a secure websocket that proxies information.  Cattle currently uses it to grab information from "cadvisor".  Here in this new action API, I plan to call docker with appropriate input parameters required for fetching the logs of a container.

**Comment by will-chan** [comment]
You should probably create a /rancherio/rancher feature request as subtasks for this will most likely result in development in both the cattle and ui projects. A couple of questions:

1. What can the user actually do?
2. Can user tail the logs?
3. Can user search for the logs?
4. Can users download the logs directly from the web interface?
5. Can users search through the logs?

**Comment by cjellick** [comment]
Done: https://github.com/rancherio/cattle/pull/210
